#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times and "Hi" in 9th iteration times

counter=0
while [ $counter -lt 10 ];
do
    if [ $counter -eq 9 ]
    then
echo "Hi"
    fi
    echo "Best School"
    let counter=counter+1
done
