#!/usr/bin/env bash
#  Script bash that displays the time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ];
do
    echo "Hour: $h"
    m=1
    while [ $m -le 59 ];
    do
echo  $m
let m=m+1
    done
    let h=h+1
done
