#!/usr/bin/env bash
# Script that displaying To infinity and beyond indefinitely and displays

while true 
do
    echo "To infinity and beyond"
    sleep 2
    trap '"echo I am invincible!!!"' SIGTERM
done
