#!/usr/bin/env bash
# Script that displaying To infinity and beyond indefinitely and displays

while [true ]
do
    trap "echo I am invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
